import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Auth
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'create_account': 'Create Account',
      'login': 'Login',
      'logout': 'Logout',
      
      // Role Selection
      'select_role': 'Select Your Role',
      'role_description': 'Choose the role that best describes your involvement in the food supply chain',
      'farmer': 'Farmer',
      'consumer': 'Consumer',
      'food_distributor': 'Food Distributor',
      'transporter': 'Transporter',
      'farmer_description': 'Grow and harvest crops, raise livestock',
      'consumer_description': 'Purchase and consume food products',
      'distributor_description': 'Distribute food products to markets',
      'transporter_description': 'Transport food products between locations',
      'continue': 'Continue',
      
      // Onboarding
      'welcome': 'Welcome to FarmLink',
      'connecting_farmers': 'Connecting Farmers with Consumers',
      'fresh_produce': 'Fresh Produce Direct from Farm',
      'secure_transactions': 'Secure and Transparent Transactions',
      'get_started': 'Get Started',
      'skip': 'Skip',
      'next': 'Next',
      
      // Settings
      'settings': 'Settings',
      'switch_to_consumer': 'Switch to Consumer',
      'language': 'Language',
      'language_changed': 'Language changed successfully',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'help': 'Help',
      'about': 'About',
      
      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'home': 'Home',
      'search': 'Search',
      'menu': 'Menu',
      
      // Validation
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'confirm_password_required': 'Please confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'invalid_email': 'Please enter a valid email address',
      
      // Dashboard
      'dashboard': 'Dashboard',
      'my_products': 'My Products',
      'orders': 'Orders',
      'analytics': 'Analytics',
      'messages': 'Messages',
      
      // Farmer Dashboard
      'crops': 'Crops',
      'delivery': 'Delivery',
      'hello': 'Hello',
      'farm_statistics': 'Farm Statistics',
      'active_crops': 'Active Crops',
      'sold_crops': 'Sold Crops',
      'pending_crops': 'Pending Crops',
      'this_month': 'This Month',
      'quick_actions': 'Quick Actions',
      'add_new_crop': 'Add New Crop',
      'add_new_crop_desc': 'List your fresh produce for bidding',
      'ai_crop_advisory': 'AI Crop Advisory',
      'ai_crop_advisory_desc': 'Get AI-powered farming advice and insights',
      'weather_forecast': 'Weather Forecast',
      'weather_forecast_desc': 'Check weather conditions for farming decisions',
      'refresh_statistics': 'Refresh Statistics',
      
      // Weather
      'weather_forecast_title': 'Weather Forecast',
      'real_time_weather': 'Real-time weather data',
      'loading_weather': 'Loading weather data...',
      'current_location': 'Current Location',
      'select_city': 'Select City',
      'current_weather': 'Current Weather',
      'farming_recommendations': 'Farming Recommendations',
      'irrigation': 'Irrigation',
      'planting': 'Planting',
      'pest_control': 'Pest Control',
      'refresh_weather': 'Refresh Weather Data',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'pressure': 'Pressure',
      
      // Crop Listing Screen
      'my_crops': 'My Crops',
      'pending': 'Pending',
      'active': 'Active',
      'expired': 'Expired',
      'all': 'All',
      'no_pending_crops': 'No pending crops',
      'no_active_crops': 'No active crops',
      'no_expired_crops': 'No expired crops',
      'no_crops_found': 'No crops found',
      'start_adding_crops': 'Start adding crops to see them here',
      'image_not_available': 'Image not available',
      'quantity': 'Quantity',
      'min_bid': 'Min Bid',
      'pickup_location': 'Pickup Location',
      'bidding_starts': 'Bidding Starts',
      'time_until_start': 'Time Until Start',
      'time_left': 'Time Left',
      'total_bids': 'Total Bids',
      'highest_bid': 'Highest Bid',
      'sold': 'Sold',
      'unknown': 'Unknown',
      'bid_history': 'Bid History',
      'confirm': 'Confirm',
      'no_bids_received': 'No bids received',
      'winner': 'Winner',
      'sold_to': 'Sold to',
      'delete_crop': 'Delete Crop',
      'delete_crop_confirm': 'Are you sure you want to delete',
      'action_cannot_undone': 'This action cannot be undone.',
      'crop_deleted_success': 'Crop deleted successfully',
      'failed_to_delete': 'Failed to delete crop',
      'bidding_history': 'Bidding History',
      'bidding_summary': 'Bidding Summary',
      'retry': 'Retry',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'Delivery Tracking',
      'please_log_in': 'Please log in',
      'no_deliveries': 'No deliveries in progress',
      'delivery_tracking_desc': 'Delivery tracking will appear here once transporters accept your orders',
      'buyer': 'Buyer',
      'amount': 'Amount',
      'pickup': 'Pickup',
      'waiting_transporter': 'Waiting for Transporter',
      'track_delivery': 'Track Delivery',
      'confirm_received': 'Confirm Received',
      'delivery_timeline': 'Delivery Timeline',
      'order_created': 'Order Created',
      'transporter_accepted': 'Transporter Accepted',
      'in_transit': 'In Transit',
      'delivered': 'Delivered',
      'estimated_delivery': 'Estimated Delivery',
      'waiting': 'Waiting',
      'accepted': 'Accepted',
      
      // Analytics Screen
      'analytics_earnings': 'Analytics & Earnings',
      'overview': 'Overview',
      'earnings': 'Earnings',
      'no_analytics_data': 'No analytics data available',
      'key_metrics': 'Key Metrics',
      'total_earnings': 'Total Earnings',
      'completed_orders': 'Completed Orders',
      'success_rate': 'Success Rate',
      'avg_order_value': 'Avg Order Value',
      'total_crops_listed': 'Total Crops Listed',
      'crops_sold': 'Crops Sold',
      'active_listings': 'Active Listings',
      'total_quantity_label': 'Total Quantity',
      'pending_orders': 'Pending Orders',
      'deliveries_completed': 'Deliveries Completed',
      'recent_activity': 'Recent Activity',
      'monthly_breakdown': 'Monthly Breakdown',
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',
      
      // Errors
      'network_error': 'Network error. Please check your connection.',
      'unknown_error': 'An unknown error occurred.',
      'auth_error': 'Authentication error.',
    },
    'si': {
      // Auth
      'sign_up': 'ලියාපදිංචි වන්න',
      'sign_in': 'පිවිසෙන්න',
      'email': 'විද්‍යුත් තැපෑල',
      'password': 'මුරපදය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'forgot_password': 'මුරපදය අමතක වුණා?',
      'dont_have_account': 'ගිණුමක් නැද්ද?',
      'already_have_account': 'දැනටමත් ගිණුමක් තිබේද?',
      'create_account': 'ගිණුම සාදන්න',
      'login': 'පිවිසෙන්න',
      'logout': 'පිටවීම',
      
      // Role Selection
      'select_role': 'ඔබේ කාර්යභාරය තෝරන්න',
      'role_description': 'ආහාර සැපයුම් දාමයේ ඔබේ සහභාගීත්වය හොඳින් විස්තර කරන කාර්යභාරය තෝරන්න',
      'farmer': 'ගොවියා',
      'consumer': 'පාරිභෝගිකයා',
      'food_distributor': 'ආහාර බෙදාහරින්නා',
      'transporter': 'ප්‍රවාහනකරු',
      'farmer_description': 'බෝග වගා කර අස්වැන්න ලබා ගැනීම, ගවයින් ඇති කිරීම',
      'consumer_description': 'ආහාර නිෂ්පාදන මිලදී ගැනීම සහ පරිභෝජනය කිරීම',
      'distributor_description': 'වෙළඳපොළවලට ආහාර නිෂ්පාදන බෙදාහරින්න',
      'transporter_description': 'ස්ථාන අතර ආහාර නිෂ්පාදන ප්‍රවාහනය කරන්න',
      'continue': 'ඉදිරියට',
      
      // Onboarding
      'welcome': 'FarmLink වෙත සාදරයෙන් පිළිගනිමු',
      'connecting_farmers': 'ගොවියන් පාරිභෝගිකයින් සමඟ සම්බන්ධ කිරීම',
      'fresh_produce': 'ගොවිපලෙන් සෘජුවම නැවුම් නිෂ්පාදන',
      'secure_transactions': 'ආරක්ෂිත සහ පාරදෘශ්‍ය ගනුදෙනු',
      'get_started': 'ආරම්භ කරන්න',
      'skip': 'මඟ හරින්න',
      'next': 'ඊළඟ',
      
      // Settings
      'settings': 'සැකසුම්',
      'switch_to_consumer': 'පාරිභෝගිකයාට මාරු වන්න',
      'language': 'භාෂාව',
      'language_changed': 'භාෂාව සාර්ථකව වෙනස් කරන ලදී',
      'profile': 'පැතිකඩ',
      'notifications': 'දැනුම්දීම්',
      'privacy': 'පෞද්ගලිකත්වය',
      'help': 'උදව්',
      'about': 'ගැන',
      
      // Common
      'loading': 'පූරණය වෙමින්...',
      'error': 'දෝෂය',
      'success': 'සාර්ථකයි',
      'cancel': 'අවලංගු කරන්න',
      'save': 'සුරැකින්න',
      'delete': 'මකන්න',
      'edit': 'සංස්කරණය',
      'back': 'ආපසු',
      'home': 'මුල් පිටුව',
      'search': 'සොයන්න',
      'menu': 'මෙනුව',
      
      // Validation
      'email_required': 'විද්‍යුත් තැපෑල අවශ්‍ය වේ',
      'password_required': 'මුරපදය අවශ්‍ය වේ',
      'confirm_password_required': 'කරුණාකර ඔබේ මුරපදය තහවුරු කරන්න',
      'passwords_dont_match': 'මුරපද නොගැලපේ',
      'password_too_short': 'මුරපදය අවම වශයෙන් අකුරු 6 ක් විය යුතුය',
      'invalid_email': 'කරුණාකර වලංගු විද්‍යුත් තැපෑලක් ඇතුළත් කරන්න',
      
      // Dashboard
      'dashboard': 'උපකරණ පුවරුව',
      'my_products': 'මගේ නිෂ්පාදන',
      'orders': 'ඇණවුම්',
      'analytics': 'විශ්ලේෂණ',
      'messages': 'පණිවිඩ',
      
      // Farmer Dashboard
      'crops': 'බෝග',
      'delivery': 'බෙදාහැරීම',
      'hello': 'ආයුබෝවන්',
      'farm_statistics': 'ගොවිපල සංඛ්‍යාලේඛන',
      'active_crops': 'සක්‍රිය බෝග',
      'sold_crops': 'විකුණූ බෝග',
      'pending_crops': 'පොරොත්තු බෝග',
      'this_month': 'මේ මාසය',
      'quick_actions': 'ඉක්මන් ක්‍රියා',
      'add_new_crop': 'නව බෝගයක් එකතු කරන්න',
      'add_new_crop_desc': 'ඔබේ නැවුම් නිෂ්පාදන ලංසු සඳහා ලැයිස්තුගත කරන්න',
      'ai_crop_advisory': 'AI බෝග උපදේශන',
      'ai_crop_advisory_desc': 'AI බලයෙන් ක්‍රියාත්මක වන ගොවිතැන් උපදෙස් සහ තීක්ෂ්ණතා ලබා ගන්න',
      'weather_forecast': 'කාලගුණ පුරෝකථනය',
      'weather_forecast_desc': 'ගොවිතැන් තීරණ සඳහා කාලගුණ තත්ත්වයන් පරීක්ෂා කරන්න',
      'refresh_statistics': 'සංඛ්‍යාලේඛන නැවුම් කරන්න',
      
      // Weather
      'weather_forecast_title': 'කාලගුණ පුරෝකථනය',
      'real_time_weather': 'තත්‍ය කාලීන කාලගුණ දත්ත',
      'loading_weather': 'කාලගුණ දත්ත පූරණය වෙමින්...',
      'current_location': 'වර්තමාන ස්ථානය',
      'select_city': 'නගරය තෝරන්න',
      'current_weather': 'වර්තමාන කාලගුණය',
      'farming_recommendations': 'ගොවිතැන් නිර්දේශ',
      'irrigation': 'වාරිමාර්ග',
      'planting': 'වගා කිරීම',
      'pest_control': 'පළිබෝධ පාලනය',
      'refresh_weather': 'කාලගුණ දත්ත නැවුම් කරන්න',
      'humidity': 'ආර්ද්‍රතාව',
      'wind': 'සුළඟ',
      'pressure': 'පීඩනය',
      
      // Crop Listing Screen
      'my_crops': 'මගේ බෝග',
      'pending': 'පොරොත්තු',
      'active': 'සක්‍රිය',
      'expired': 'කල් ඉකුත්',
      'all': 'සියල්ල',
      'no_pending_crops': 'පොරොත්තු බෝග නැත',
      'no_active_crops': 'සක්‍රිය බෝග නැත',
      'no_expired_crops': 'කල් ඉකුත් බෝග නැත',
      'no_crops_found': 'බෝග හමු නොවීය',
      'start_adding_crops': 'මෙහි ඒවා දැකීමට බෝග එකතු කිරීම ආරම්භ කරන්න',
      'image_not_available': 'රූපය ලබා ගත නොහැක',
      'quantity': 'ප්‍රමාණය',
      'min_bid': 'අවම ලංසුව',
      'pickup_location': 'එකතු කරන ස්ථානය',
      'bidding_starts': 'ලංසු ආරම්භය',
      'time_until_start': 'ආරම්භය දක්වා කාලය',
      'time_left': 'ඉතිරි කාලය',
      'total_bids': 'මුළු ලංසු',
      'highest_bid': 'ඉහළම ලංසුව',
      'sold': 'විකුණා ඇත',
      'unknown': 'නොදනී',
      'bid_history': 'ලංසු ඉතිහාසය',
      'confirm': 'තහවුරු කරන්න',
      'no_bids_received': 'ලංසු ලැබී නැත',
      'winner': 'ජයග්‍රාහකයා',
      'sold_to': 'විකුණා ඇත',
      'delete_crop': 'බෝගය මකන්න',
      'delete_crop_confirm': 'ඔබට මකා දැමීමට අවශ්‍යද',
      'action_cannot_undone': 'මෙම ක්‍රියාව අහෝසි කළ නොහැක.',
      'crop_deleted_success': 'බෝගය සාර්ථකව මකා ඇත',
      'failed_to_delete': 'බෝගය මකා දැමීමට අසමත් විය',
      'bidding_history': 'ලංසු ඉතිහාසය',
      'bidding_summary': 'ලංසු සාරාංශය',
      'retry': 'නැවත උත්සාහ කරන්න',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'බෙදාහැරීම් ලුහුබැඳීම',
      'please_log_in': 'කරුණාකර පිවිසෙන්න',
      'no_deliveries': 'ප්‍රගතියේ බෙදාහැරීම් නැත',
      'delivery_tracking_desc': 'ප්‍රවාහන නියෝජිතයින් ඔබේ ඇණවුම් පිළිගත් පසු බෙදාහැරීම් ලුහුබැඳීම මෙහි දිස්වේ',
      'buyer': 'ගැනුම්කරු',
      'amount': 'මුදල',
      'pickup': 'එකතු කිරීම',
      'waiting_transporter': 'ප්‍රවාහනකරු සඳහා රැඳී සිටිමින්',
      'track_delivery': 'බෙදාහැරීම ලුහුබඳින්න',
      'confirm_received': 'ලැබීම තහවුරු කරන්න',
      'delivery_timeline': 'බෙදාහැරීම් කාල සටහන',
      'order_created': 'ඇණවුම නිර්මාණය කර ඇත',
      'transporter_accepted': 'ප්‍රවාහනකරු පිළිගෙන ඇත',
      'in_transit': 'ප්‍රවාහනයේ',
      'delivered': 'බෙදා හැර ඇත',
      'estimated_delivery': 'ඇස්තමේන්තුගත බෙදාහැරීම',
      'waiting': 'රැඳී සිටිමින්',
      'accepted': 'පිළිගත්',
      
      // Analytics Screen
      'analytics_earnings': 'විශ්ලේෂණ සහ ඉපැයීම්',
      'overview': 'දළ විශ්ලේෂණය',
      'earnings': 'ඉපැයීම්',
      'no_analytics_data': 'විශ්ලේෂණ දත්ත නොමැත',
      'key_metrics': 'ප්‍රධාන මිණුම්',
      'total_earnings': 'මුළු ඉපැයීම්',
      'completed_orders': 'සම්පූර්ණ කළ ඇණවුම්',
      'success_rate': 'සාර්ථක අනුපාතය',
      'avg_order_value': 'සාමාන්‍ය ඇණවුම් වටිනාකම',
      'total_crops_listed': 'ලැයිස්තුගත මුළු බෝග',
      'crops_sold': 'විකුණූ බෝග',
      'active_listings': 'සක්‍රිය ලැයිස්තු',
      'total_quantity_label': 'මුළු ප්‍රමාණය',
      'pending_orders': 'පොරොත්තු ඇණවුම්',
      'deliveries_completed': 'බෙදාහැරීම් සම්පූර්ණයි',
      'recent_activity': 'මෑත ක්‍රියාකාරකම්',
      'monthly_breakdown': 'මාසික බෙදීම',
      'month_jan': 'ජන',
      'month_feb': 'පෙබ',
      'month_mar': 'මාර්',
      'month_apr': 'අප්‍රේ',
      'month_may': 'මැයි',
      'month_jun': 'ජූනි',
      'month_jul': 'ජූලි',
      'month_aug': 'අගෝ',
      'month_sep': 'සැප්',
      'month_oct': 'ඔක්',
      'month_nov': 'නොවැ',
      'month_dec': 'දෙසැ',
      
      // Errors
      'network_error': 'ජාල දෝෂය. කරුණාකර ඔබේ සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'unknown_error': 'නොදන්නා දෝෂයක් සිදු විය.',
      'auth_error': 'සත්‍යාපන දෝෂය.',
    },
    'ta': {
      // Auth
      'sign_up': 'பதிவு செய்க',
      'sign_in': 'உள்நுழைய',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'create_account': 'கணக்கு உருவாக்கு',
      'login': 'உள்நுழைய',
      'logout': 'வெளியேறு',
      
      // Role Selection
      'select_role': 'உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
      'role_description': 'உணவு சங்கிலியில் உங்கள் பங்கேற்பை சிறப்பாக விவரிக்கும் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
      'farmer': 'விவசாயி',
      'consumer': 'நுகர்வோர்',
      'food_distributor': 'உணவு விநியோகஸ்தர்',
      'transporter': 'போக்குவரத்து',
      'farmer_description': 'பயிர்களை வளர்த்து அறுவடை செய்தல், கால்நடைகளை வளர்த்தல்',
      'consumer_description': 'உணவு பொருட்களை வாங்கி பயன்படுத்துதல்',
      'distributor_description': 'சந்தைகளுக்கு உணவு பொருட்களை விநியோகித்தல்',
      'transporter_description': 'இடங்களுக்கு இடையே உணவு பொருட்களை போக்குவரத்து செய்தல்',
      'continue': 'தொடரவும்',
      
      // Onboarding
      'welcome': 'FarmLink க்கு வரவேற்கிறோம்',
      'connecting_farmers': 'விவசாயிகளை நுகர்வோருடன் இணைத்தல்',
      'fresh_produce': 'பண்ணையிலிருந்து நேரடியாக புதிய பொருட்கள்',
      'secure_transactions': 'பாதுகாப்பான மற்றும் வெளிப்படையான பரிவர்த்தனைகள்',
      'get_started': 'தொடங்கவும்',
      'skip': 'தவிர்க்கவும்',
      'next': 'அடுத்து',
      
      // Settings
      'settings': 'அமைப்புகள்',
      'switch_to_consumer': 'நுகர்வோருக்கு மாற்று',
      'language': 'மொழி',
      'language_changed': 'மொழி வெற்றிகரமாக மாற்றப்பட்டது',
      'profile': 'சுயவிவரம்',
      'notifications': 'அறிவிப்புகள்',
      'privacy': 'தனியுரிமை',
      'help': 'உதவி',
      'about': 'பற்றி',
      
      // Common
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'cancel': 'ரத்து செய்',
      'save': 'சேமி',
      'delete': 'அழி',
      'edit': 'திருத்து',
      'back': 'பின்செல்',
      'home': 'முகப்பு',
      'search': 'தேடு',
      'menu': 'மெனு',
      
      // Validation
      'email_required': 'மின்னஞ்சல் தேவை',
      'password_required': 'கடவுச்சொல் தேவை',
      'confirm_password_required': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'passwords_dont_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'password_too_short': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
      'invalid_email': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      
      // Dashboard
      'dashboard': 'டாஷ்போர்டு',
      'my_products': 'எனது பொருட்கள்',
      'orders': 'ஆர்டர்கள்',
      'analytics': 'பகுப்பாய்வு',
      'messages': 'செய்திகள்',
      
      // Farmer Dashboard
      'crops': 'பயிர்கள்',
      'delivery': 'விநியோகம்',
      'hello': 'வணக்கம்',
      'farm_statistics': 'பண்ணை புள்ளிவிவரங்கள்',
      'active_crops': 'செயல்படும் பயிர்கள்',
      'sold_crops': 'விற்கப்பட்ட பயிர்கள்',
      'pending_crops': 'நிலுவையில் உள்ள பயிர்கள்',
      'this_month': 'இந்த மாதம்',
      'quick_actions': 'விரைவு செயல்கள்',
      'add_new_crop': 'புதிய பயிர் சேர்க்கவும்',
      'add_new_crop_desc': 'ஏலத்திற்கு உங்கள் புதிய பொருட்களை பட்டியலிடவும்',
      'ai_crop_advisory': 'AI பயிர் ஆலோசனை',
      'ai_crop_advisory_desc': 'AI-இயக்கப்பட்ட விவசாய ஆலோசனை மற்றும் நுண்ணறிவுகளைப் பெறவும்',
      'weather_forecast': 'வானிலை முன்னறிவிப்பு',
      'weather_forecast_desc': 'விவசாய முடிவுகளுக்கான வானிலை நிலைமைகளை சரிபார்க்கவும்',
      'refresh_statistics': 'புள்ளிவிவரங்களை புதுப்பிக்கவும்',
      
      // Weather
      'weather_forecast_title': 'வானிலை முன்னறிவிப்பு',
      'real_time_weather': 'நேரடி வானிலை தரவு',
      'loading_weather': 'வானிலை தரவை ஏற்றுகிறது...',
      'current_location': 'தற்போதைய இடம்',
      'select_city': 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
      'current_weather': 'தற்போதைய வானிலை',
      'farming_recommendations': 'விவசாய பரிந்துரைகள்',
      'irrigation': 'நீர்ப்பாசனம்',
      'planting': 'நடவு',
      'pest_control': 'பூச்சி கட்டுப்பாடு',
      'refresh_weather': 'வானிலை தரவை புதுப்பிக்கவும்',
      'humidity': 'ஈரப்பதம்',
      'wind': 'காற்று',
      'pressure': 'அழுத்தம்',
      
      // Crop Listing Screen
      'my_crops': 'எனது பயிர்கள்',
      'pending': 'நிலுவையில்',
      'active': 'செயல்படும்',
      'expired': 'காலாவதியானது',
      'all': 'அனைத்தும்',
      'no_pending_crops': 'நிலுவையில் உள்ள பயிர்கள் இல்லை',
      'no_active_crops': 'செயல்படும் பயிர்கள் இல்லை',
      'no_expired_crops': 'காலாவதியான பயிர்கள் இல்லை',
      'no_crops_found': 'பயிர்கள் கிடைக்கவில்லை',
      'start_adding_crops': 'இங்கே காண பயிர்களைச் சேர்க்கத் தொடங்குங்கள்',
      'image_not_available': 'படம் கிடைக்கவில்லை',
      'quantity': 'அளவு',
      'min_bid': 'குறைந்தபட்ச ஏலம்',
      'pickup_location': 'எடுக்கும் இடம்',
      'bidding_starts': 'ஏலம் தொடங்கும்',
      'time_until_start': 'தொடக்கம் வரை நேரம்',
      'time_left': 'மீதமுள்ள நேரம்',
      'total_bids': 'மொத்த ஏலங்கள்',
      'highest_bid': 'அதிகபட்ச ஏலம்',
      'sold': 'விற்கப்பட்டது',
      'unknown': 'தெரியாத',
      'bid_history': 'ஏல வரலாறு',
      'confirm': 'உறுதிப்படுத்து',
      'no_bids_received': 'ஏலங்கள் பெறப்படவில்லை',
      'winner': 'வெற்றியாளர்',
      'sold_to': 'விற்கப்பட்டது',
      'delete_crop': 'பயிரை அழி',
      'delete_crop_confirm': 'நீங்கள் நிச்சயமாக அழிக்க விரும்புகிறீர்களா',
      'action_cannot_undone': 'இந்த செயலை மாற்ற இயலாது.',
      'crop_deleted_success': 'பயிர் வெற்றிகரமாக அழிக்கப்பட்டது',
      'failed_to_delete': 'பயிரை அழிக்க தோல்வி',
      'bidding_history': 'ஏல வரலாறு',
      'bidding_summary': 'ஏல சுருக்கம்',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'விநியோக கண்காணிப்பு',
      'please_log_in': 'தயவுசெய்து உள்நுழையவும்',
      'no_deliveries': 'விநியோகங்கள் முன்னேற்றத்தில் இல்லை',
      'delivery_tracking_desc': 'போக்குவரத்து நிறுவனங்கள் உங்கள் ஆர்டர்களை ஏற்றுக்கொண்டதும் விநியோக கண்காணிப்பு இங்கே தோன்றும்',
      'buyer': 'வாங்குபவர்',
      'amount': 'தொகை',
      'pickup': 'எடுத்தல்',
      'waiting_transporter': 'போக்குவரத்துக்காக காத்திருக்கிறது',
      'track_delivery': 'விநியோகத்தைக் கண்காணிக்கவும்',
      'confirm_received': 'பெறப்பட்டதை உறுதிப்படுத்து',
      'delivery_timeline': 'விநியோக காலவரிசை',
      'order_created': 'ஆர்டர் உருவாக்கப்பட்டது',
      'transporter_accepted': 'போக்குவரத்து ஏற்றுக்கொள்ளப்பட்டது',
      'in_transit': 'போக்குவரத்தில்',
      'delivered': 'வழங்கப்பட்டது',
      'estimated_delivery': 'மதிப்பிடப்பட்ட விநியோகம்',
      'waiting': 'காத்திருக்கிறது',
      'accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
      
      // Analytics Screen
      'analytics_earnings': 'பகுப்பாய்வு & வருமானம்',
      'overview': 'கண்ணோட்டம்',
      'earnings': 'வருமானம்',
      'no_analytics_data': 'பகுப்பாய்வு தரவு கிடைக்கவில்லை',
      'key_metrics': 'முக்கிய அளவீடுகள்',
      'total_earnings': 'மொத்த வருமானம்',
      'completed_orders': 'முடிக்கப்பட்ட ஆர்டர்கள்',
      'success_rate': 'வெற்றி விகிதம்',
      'avg_order_value': 'சராசரி ஆர்டர் மதிப்பு',
      'total_crops_listed': 'பட்டியலிடப்பட்ட மொத்த பயிர்கள்',
      'crops_sold': 'விற்கப்பட்ட பயிர்கள்',
      'active_listings': 'செயல்படும் பட்டியல்கள்',
      'total_quantity_label': 'மொத்த அளவு',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'deliveries_completed': 'விநியோகங்கள் முடிந்தது',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'monthly_breakdown': 'மாதாந்திர பிரிவு',
      'month_jan': 'ஜன',
      'month_feb': 'பிப்',
      'month_mar': 'மார்',
      'month_apr': 'ஏப்',
      'month_may': 'மே',
      'month_jun': 'ஜூன்',
      'month_jul': 'ஜூலை',
      'month_aug': 'ஆக',
      'month_sep': 'செப்',
      'month_oct': 'அக்',
      'month_nov': 'நவ',
      'month_dec': 'டிச',
      
      // Errors
      'network_error': 'பிணைய பிழை. உங்கள் இணைப்பை சரிபார்க்கவும்.',
      'unknown_error': 'தெரியாத பிழை ஏற்பட்டது.',
      'auth_error': 'அங்கீகார பிழை.',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['en']![key] ?? 
           key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'si', 'ta'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
