import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Auth
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'create_account': 'Create Account',
      'login': 'Login',
      'logout': 'Logout',
      
      // Role Selection
      'select_role': 'Select Your Role',
      'role_description': 'Choose the role that best describes your involvement in the food supply chain',
      'farmer': 'Farmer',
      'consumer': 'Consumer',
      'food_distributor': 'Food Distributor',
      'transporter': 'Transporter',
      'farmer_description': 'Grow and harvest crops, raise livestock',
      'consumer_description': 'Purchase and consume food products',
      'distributor_description': 'Distribute food products to markets',
      'transporter_description': 'Transport food products between locations',
      'continue': 'Continue',
      
      // Onboarding
      'welcome': 'Welcome to FarmLink',
      'connecting_farmers': 'Connecting Farmers with Consumers',
      'fresh_produce': 'Fresh Produce Direct from Farm',
      'secure_transactions': 'Secure and Transparent Transactions',
      'get_started': 'Get Started',
      'skip': 'Skip',
      'next': 'Next',
      
      // Settings
      'settings': 'Settings',
      'switch_to_consumer': 'Switch to Consumer',
      'language': 'Language',
      'language_changed': 'Language changed successfully',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'help': 'Help',
      'about': 'About',
      
      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'home': 'Home',
      'history': 'History',
      'search': 'Search',
      'menu': 'Menu',
      
      // Validation
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'confirm_password_required': 'Please confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'invalid_email': 'Please enter a valid email address',
      
      // Dashboard
      'dashboard': 'Dashboard',
      'my_products': 'My Products',
      'orders': 'Orders',
      'analytics': 'Analytics',
      'messages': 'Messages',
      
      // Farmer Dashboard
      'crops': 'Crops',
      'delivery': 'Delivery',
      'hello': 'Hello',
      'farm_statistics': 'Farm Statistics',
      'active_crops': 'Active Crops',
      'sold_crops': 'Sold Crops',
      'pending_crops': 'Pending Crops',
      'this_month': 'This Month',
      'quick_actions': 'Quick Actions',
      'add_new_crop': 'Add New Crop',
      'add_new_crop_desc': 'List your fresh produce for bidding',
      'ai_crop_advisory': 'AI Crop Advisory',
      'ai_crop_advisory_desc': 'Get AI-powered farming advice and insights',
      'weather_forecast': 'Weather Forecast',
      'weather_forecast_desc': 'Check weather conditions for farming decisions',
      'refresh_statistics': 'Refresh Statistics',
      
      // Weather
      'weather_forecast_title': 'Weather Forecast',
      'real_time_weather': 'Real-time weather data',
      'loading_weather': 'Loading weather data...',
      'current_location': 'Current Location',
      'select_city': 'Select City',
      'current_weather': 'Current Weather',
      'farming_recommendations': 'Farming Recommendations',
      'irrigation': 'Irrigation',
      'planting': 'Planting',
      'pest_control': 'Pest Control',
      'refresh_weather': 'Refresh Weather Data',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'pressure': 'Pressure',
      
      // Crop Listing Screen
      'my_crops': 'My Crops',
      'pending': 'Pending',
      'active': 'Active',
      'expired': 'Expired',
      'all': 'All',
      'no_pending_crops': 'No pending crops',
      'no_active_crops': 'No active crops',
      'no_expired_crops': 'No expired crops',
      'no_crops_found': 'No crops found',
      'start_adding_crops': 'Start adding crops to see them here',
      'image_not_available': 'Image not available',
      'quantity': 'Quantity',
      'min_bid': 'Min Bid',
      'pickup_location': 'Pickup Location',
      'bidding_starts': 'Bidding Starts',
      'time_until_start': 'Time Until Start',
      'time_left': 'Time Left',
      'total_bids': 'Total Bids',
      'highest_bid': 'Highest Bid',
      'sold': 'Sold',
      'unknown': 'Unknown',
      'bid_history': 'Bid History',
      'confirm': 'Confirm',
      'no_bids_received': 'No bids received',
      'winner': 'Winner',
      'sold_to': 'Sold to',
      'delete_crop': 'Delete Crop',
      'delete_crop_confirm': 'Are you sure you want to delete',
      'action_cannot_undone': 'This action cannot be undone.',
      'crop_deleted_success': 'Crop deleted successfully',
      'failed_to_delete': 'Failed to delete crop',
      'bidding_history': 'Bidding History',
      'bidding_summary': 'Bidding Summary',
      'retry': 'Retry',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'Delivery Tracking',
      'please_log_in': 'Please log in',
      'no_deliveries': 'No deliveries in progress',
      'delivery_tracking_desc': 'Delivery tracking will appear here once transporters accept your orders',
      'buyer': 'Buyer',
      'amount': 'Amount',
      'pickup': 'Pickup',
      'waiting_transporter': 'Waiting for Transporter',
      'track_delivery': 'Track Delivery',
      'confirm_received': 'Confirm Received',
      'delivery_timeline': 'Delivery Timeline',
      'order_created': 'Order Created',
      'transporter_accepted': 'Transporter Accepted',
      'in_transit': 'In Transit',
      'delivered': 'Delivered',
      'estimated_delivery': 'Estimated Delivery',
      'waiting': 'Waiting',
      'accepted': 'Accepted',
      
      // Analytics Screen
      'analytics_earnings': 'Analytics & Earnings',
      'overview': 'Overview',
      'earnings': 'Earnings',
      'no_analytics_data': 'No analytics data available',
      'key_metrics': 'Key Metrics',
      'total_earnings': 'Total Earnings',
      'completed_orders': 'Completed Orders',
      'success_rate': 'Success Rate',
      'avg_order_value': 'Avg Order Value',
      'total_crops_listed': 'Total Crops Listed',
      'crops_sold': 'Crops Sold',
      'active_listings': 'Active Listings',
      'total_quantity_label': 'Total Quantity',
      'pending_orders': 'Pending Orders',
      'deliveries_completed': 'Deliveries Completed',
      'recent_activity': 'Recent Activity',
      'monthly_breakdown': 'Monthly Breakdown',
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',
      
      // Distributor Dashboard
      'distributor': 'Distributor',
      'distributor_dashboard': 'Distributor Dashboard',
      'marketplace': 'Marketplace',
      'my_orders': 'My Orders',
      'products': 'Products',
      'bid_analytics': 'Bid Analytics',
      'active_auctions': 'Active auctions',
      'my_bids': 'My bids',
      'won_auctions': 'Won auctions',
      'total_spent': 'Total spent',
      'leading_now': 'Leading now',
      'ending_soon': 'Ending ≤24h',
      'last_7_days_trend': 'Last 7 days bid trend',
      'avg': 'Avg',
      'win': 'Win',
      'day': 'Day',
      'ending_soon_label': 'Ending soon',
      'ends_in': 'Ends in',
      'you_are_leading': 'You are leading',
      'not_leading': 'Not leading',
      'top_spend_by_crop': 'Top spend by crop',
      'last_7_days': 'Last 7 days',
      'last_30_days': 'Last 30 days',
      
      // Marketplace Screen
      'no_crops_available': 'No crops available',
      'no_active_auctions': 'No active auctions or won crops to display',
      'current_highest': 'Current Highest',
      'your_bid': 'Your Bid',
      'bidding_history_count': 'Bidding History',
      'bids': 'bids',
      'you_won_auction': 'You won this auction! Final price',
      'sold_to_bidder': 'Sold to',
      'highest_bidder': 'Highest Bidder',
      'no_bids_placed': 'No bids placed - Auction ended',
      'place_order': 'Place Order',
      'auction_ended': 'Auction ended.',
      'won': 'won',
      'update_bid': 'Update Bid',
      'place_bid': 'Place Bid',
      'place_your_bid': 'Place Your Bid',
      'your_bid_amount': 'Your Bid Amount',
      'enter_amount_lkr': 'Enter amount in LKR',
      'bid_must_be_at_least': 'Bid must be at least',
      'bid_placed_success': 'Bid placed successfully!',
      'failed_place_bid': 'Failed to place bid',
      'update_your_bid': 'Update Your Bid',
      'your_current_bid': 'Your Current Bid',
      'new_bid_amount': 'New Bid Amount',
      'enter_new_amount': 'Enter new amount in LKR',
      'new_bid_must_be_higher': 'New bid must be higher than',
      'bid_updated_success': 'Bid updated successfully!',
      'failed_update_bid': 'Failed to update bid',
      'close': 'Close',
      
      // My Orders Screen
      'farmer_orders': 'Farmer Orders',
      'consumer_orders': 'Consumer Orders',
      
      // My Products Screen
      'delete_product': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete',
      'product_deleted_success': 'Product deleted successfully!',
      'no_products_yet': 'No products yet',
      'add_first_product': 'Add your first product to start selling',
      'add_product': 'Add Product',
      'search_products': 'Search products...',
      'available': 'Available',
      'low_stock': 'Low stock',
      'out_of_stock': 'Out of stock',
      'total_value': 'Total Value',
      'set_baseline': 'Set baseline',
      'baseline_set': 'Baseline set to current quantity',
      'edit_product': 'Edit Product',
      'adjust_stock_kg': 'Adjust Stock (kg)',
      'apply': 'Apply',
      'stock_adjusted': 'Stock adjusted',
      'inventory_overview': 'Inventory Overview',
      
      // Errors
      'network_error': 'Network error. Please check your connection.',
      'unknown_error': 'An unknown error occurred.',
      'auth_error': 'Authentication error.',
      
      // Transporter Dashboard
      'transporter_dashboard': 'Transporter Dashboard',
      'my_transports': 'My Transports',
      'available_status': 'available',
      'hi': 'Hi',
      'deliver_with_care': 'Let\'s deliver with care today',
      'available_deliveries': 'Available Deliveries',
      'active_deliveries': 'Active Deliveries',
      'all_time': 'All Time',
      'transport_orders': 'Transport Orders',
      'view_details': 'View Details',
      'no_transport_orders': 'No transport orders',
      'no_transport_orders_desc': 'Transport orders will appear here once you accept delivery requests',
      'earnings_this_week': 'Earnings This Week',
      'recent_deliveries': 'Recent Deliveries',
      'from': 'From',
      'to': 'To',
      'completed_on': 'Completed on',
      'no_recent_deliveries': 'No recent deliveries',
      'start_delivering': 'Start delivering to see your history',
      'earnings_breakdown': 'Earnings Breakdown',
      'completed_deliveries': 'Completed Deliveries',
      'avg_earnings_per_delivery': 'Avg Earnings/Delivery',
      'total_distance_covered': 'Total Distance Covered',
      'performance_metrics': 'Performance Metrics',
      'acceptance_rate': 'Acceptance Rate',
      'on_time_delivery': 'On-Time Delivery',
      'customer_rating': 'Customer Rating',
      'earnings_trend': 'Earnings Trend',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      
      // Transporter Settings
      'transporter_settings': 'Transporter Settings',
      'vehicle_details': 'Vehicle Details',
      'manage_vehicle_info': 'Manage your vehicle information',
      'service_areas': 'Service Areas',
      'set_service_areas': 'Set your delivery service areas',
      'maintenance_schedule': 'Maintenance Schedule',
      'manage_maintenance': 'Manage vehicle maintenance',
      'role_management': 'Role Management',
      'current_transporter': 'Current: Transporter',
      'switch_role': 'Switch Role',
      'select_role_to_switch': 'Select a role to switch to:',
      'switch_to_role': 'Switch to',
      'manage_notification_prefs': 'Manage notification preferences',
      'privacy_security_settings': 'Privacy and security settings',
      'get_help_support': 'Get help and support',
      'app_info_version': 'App information and version',
      'profile_photo_updated': 'Profile photo updated',
      'failed_update_photo': 'Failed to update photo',
      'no_active_role_found': 'No active role found',
      
      // Delivery Orders Screen
      'schedule': 'Schedule',
      'no_available_deliveries': 'No available deliveries',
      'new_delivery_orders_appear': 'New delivery orders will appear here',
      'no_scheduled_deliveries': 'No scheduled deliveries',
      'tap_to_schedule': 'Tap calendar icon to schedule deliveries',
      'dropoff': 'Dropoff',
      'accept_delivery': 'Accept Delivery',
      'schedule_delivery': 'Schedule Delivery',
      'view_route': 'View Route',
      'delivery_accepted': 'Delivery accepted successfully!',
      'failed_accept_delivery': 'Failed to accept delivery',
      'select_day': 'Select Day',
      'scheduled_for': 'Scheduled for',
      'unschedule': 'Unschedule',
      'accept_all_scheduled': 'Accept All Scheduled',
      'deliveries_for': 'deliveries for',
      
      // Transport Orders Screen
      'all_orders': 'All',
      'ongoing': 'Ongoing',
      'no_orders_yet': 'No orders yet',
      'orders_appear_here': 'Accepted delivery orders will appear here',
      'no_accepted_transports': 'No accepted transports',
      'no_in_transit_transports': 'No in-transit transports',
      'no_delivered_transports': 'No delivered transports',
      'no_cancelled_transports': 'No cancelled transports',
      'accepted_transports_appear': 'Accepted transport orders will appear here',
      'in_transit_transports_appear': 'In-transit transport orders will appear here',
      'delivered_transports_appear': 'Delivered transport orders will appear here',
      'cancelled_transports_appear': 'Cancelled transport orders will appear here',
      'pickup_at': 'Pickup at',
      'deliver_to': 'Deliver to',
      'started_delivery': 'Started Delivery',
      'mark_delivered': 'Mark Delivered',
      'order_delivered': 'Order marked as delivered successfully!',
      'failed_update_status': 'Failed to update delivery status',
      'transport_order': 'Transport Order',
      'scheduled_delivery': 'Scheduled Delivery',
      'planned': 'PLANNED',
      'specific_delivery_location': 'Specific Delivery Location:',
      'delivery_fee': 'delivery fee',
      'open_in_maps': 'Open in Google Maps',
      'get_directions': 'Get Directions',
      'provide_feedback': 'Provide Feedback',
      'rate_distributor': 'Rate Distributor',
      'update_feedback': 'Update Feedback',
      'overall_rating': 'Overall Rating',
      'what_stood_out': 'What stood out? (Optional)',
      'comments_optional': 'Comments (Optional)',
      'suggestions_optional': 'Suggestions (Optional)',
      'share_issues_highlights': 'Share any issues or highlights with the distributor...',
      'suggest_improvements': 'Suggest improvements for faster and smoother delivery...',
      'please_select_rating': 'Please select a rating',
      'feedback_submitted': 'Feedback submitted!',
      'feedback_updated': 'Feedback updated!',
      'failed_to_submit': 'Failed to submit',
      
      // History Tab
      'no_delivery_history': 'No delivery history',
      'no_deliveries_found': 'No deliveries found',
      'completed_deliveries_appear': 'Completed deliveries will appear here',
      'try_different_period': 'Try selecting a different time period',
      'delivery_location': 'Delivery Location',
      'total_orders': 'Total Orders',
      'avg_order_earnings': 'Avg Per Order',
      'no_activity_yet': 'No activity yet',
      'start_accepting_deliveries': 'Start accepting deliveries to see analytics',
      
      // Earnings/Analytics
      'total_distance': 'Total Distance',
      'avg_per_delivery': 'Avg/Delivery',
      'this_month_earnings': 'This Month',
      'filter_by': 'Filter by',
      'select_month': 'Select Month',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'no_earnings_data': 'No earnings data',
      'complete_deliveries_see_earnings': 'Complete deliveries to see your earnings here',
    },
    'si': {
      // Auth
      'sign_up': 'ලියාපදිංචි වන්න',
      'sign_in': 'පිවිසෙන්න',
      'email': 'විද්‍යුත් තැපෑල',
      'password': 'මුරපදය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'forgot_password': 'මුරපදය අමතක වුණා?',
      'dont_have_account': 'ගිණුමක් නැද්ද?',
      'already_have_account': 'දැනටමත් ගිණුමක් තිබේද?',
      'create_account': 'ගිණුම සාදන්න',
      'login': 'පිවිසෙන්න',
      'logout': 'පිටවීම',
      
      // Role Selection
      'select_role': 'ඔබේ කාර්යභාරය තෝරන්න',
      'role_description': 'ආහාර සැපයුම් දාමයේ ඔබේ සහභාගීත්වය හොඳින් විස්තර කරන කාර්යභාරය තෝරන්න',
      'farmer': 'ගොවියා',
      'consumer': 'පාරිභෝගිකයා',
      'food_distributor': 'ආහාර බෙදාහරින්නා',
      'transporter': 'ප්‍රවාහනකරු',
      'farmer_description': 'බෝග වගා කර අස්වැන්න ලබා ගැනීම, ගවයින් ඇති කිරීම',
      'consumer_description': 'ආහාර නිෂ්පාදන මිලදී ගැනීම සහ පරිභෝජනය කිරීම',
      'distributor_description': 'වෙළඳපොළවලට ආහාර නිෂ්පාදන බෙදාහරින්න',
      'transporter_description': 'ස්ථාන අතර ආහාර නිෂ්පාදන ප්‍රවාහනය කරන්න',
      'continue': 'ඉදිරියට',
      
      // Onboarding
      'welcome': 'FarmLink වෙත සාදරයෙන් පිළිගනිමු',
      'connecting_farmers': 'ගොවියන් පාරිභෝගිකයින් සමඟ සම්බන්ධ කිරීම',
      'fresh_produce': 'ගොවිපලෙන් සෘජුවම නැවුම් නිෂ්පාදන',
      'secure_transactions': 'ආරක්ෂිත සහ පාරදෘශ්‍ය ගනුදෙනු',
      'get_started': 'ආරම්භ කරන්න',
      'skip': 'මඟ හරින්න',
      'next': 'ඊළඟ',
      
      // Settings
      'settings': 'සැකසුම්',
      'switch_to_consumer': 'පාරිභෝගිකයාට මාරු වන්න',
      'language': 'භාෂාව',
      'language_changed': 'භාෂාව සාර්ථකව වෙනස් කරන ලදී',
      'profile': 'පැතිකඩ',
      'notifications': 'දැනුම්දීම්',
      'privacy': 'පෞද්ගලිකත්වය',
      'help': 'උදව්',
      'about': 'ගැන',
      
      // Common
      'loading': 'පූරණය වෙමින්...',
      'error': 'දෝෂය',
      'success': 'සාර්ථකයි',
      'cancel': 'අවලංගු කරන්න',
      'save': 'සුරැකින්න',
      'delete': 'මකන්න',
      'edit': 'සංස්කරණය',
      'back': 'ආපසු',
      'home': 'මුල් පිටුව',
      'history': 'ඉතිහාසය',
      'search': 'සොයන්න',
      'menu': 'මෙනුව',
      
      // Validation
      'email_required': 'විද්‍යුත් තැපෑල අවශ්‍ය වේ',
      'password_required': 'මුරපදය අවශ්‍ය වේ',
      'confirm_password_required': 'කරුණාකර ඔබේ මුරපදය තහවුරු කරන්න',
      'passwords_dont_match': 'මුරපද නොගැලපේ',
      'password_too_short': 'මුරපදය අවම වශයෙන් අකුරු 6 ක් විය යුතුය',
      'invalid_email': 'කරුණාකර වලංගු විද්‍යුත් තැපෑලක් ඇතුළත් කරන්න',
      
      // Dashboard
      'dashboard': 'උපකරණ පුවරුව',
      'my_products': 'මගේ නිෂ්පාදන',
      'orders': 'ඇණවුම්',
      'analytics': 'විශ්ලේෂණ',
      'messages': 'පණිවිඩ',
      
      // Farmer Dashboard
      'crops': 'බෝග',
      'delivery': 'බෙදාහැරීම',
      'hello': 'ආයුබෝවන්',
      'farm_statistics': 'ගොවිපල සංඛ්‍යාලේඛන',
      'active_crops': 'සක්‍රිය බෝග',
      'sold_crops': 'විකුණූ බෝග',
      'pending_crops': 'පොරොත්තු බෝග',
      'this_month': 'මේ මාසය',
      'quick_actions': 'ඉක්මන් ක්‍රියා',
      'add_new_crop': 'නව බෝගයක් එකතු කරන්න',
      'add_new_crop_desc': 'ඔබේ නැවුම් නිෂ්පාදන ලංසු සඳහා ලැයිස්තුගත කරන්න',
      'ai_crop_advisory': 'AI බෝග උපදේශන',
      'ai_crop_advisory_desc': 'AI බලයෙන් ක්‍රියාත්මක වන ගොවිතැන් උපදෙස් සහ තීක්ෂ්ණතා ලබා ගන්න',
      'weather_forecast': 'කාලගුණ පුරෝකථනය',
      'weather_forecast_desc': 'ගොවිතැන් තීරණ සඳහා කාලගුණ තත්ත්වයන් පරීක්ෂා කරන්න',
      'refresh_statistics': 'සංඛ්‍යාලේඛන නැවුම් කරන්න',
      
      // Weather
      'weather_forecast_title': 'කාලගුණ පුරෝකථනය',
      'real_time_weather': 'තත්‍ය කාලීන කාලගුණ දත්ත',
      'loading_weather': 'කාලගුණ දත්ත පූරණය වෙමින්...',
      'current_location': 'වර්තමාන ස්ථානය',
      'select_city': 'නගරය තෝරන්න',
      'current_weather': 'වර්තමාන කාලගුණය',
      'farming_recommendations': 'ගොවිතැන් නිර්දේශ',
      'irrigation': 'වාරිමාර්ග',
      'planting': 'වගා කිරීම',
      'pest_control': 'පළිබෝධ පාලනය',
      'refresh_weather': 'කාලගුණ දත්ත නැවුම් කරන්න',
      'humidity': 'ආර්ද්‍රතාව',
      'wind': 'සුළඟ',
      'pressure': 'පීඩනය',
      
      // Crop Listing Screen
      'my_crops': 'මගේ බෝග',
      'pending': 'පොරොත්තු',
      'active': 'සක්‍රිය',
      'expired': 'කල් ඉකුත්',
      'all': 'සියල්ල',
      'no_pending_crops': 'පොරොත්තු බෝග නැත',
      'no_active_crops': 'සක්‍රිය බෝග නැත',
      'no_expired_crops': 'කල් ඉකුත් බෝග නැත',
      'no_crops_found': 'බෝග හමු නොවීය',
      'start_adding_crops': 'මෙහි ඒවා දැකීමට බෝග එකතු කිරීම ආරම්භ කරන්න',
      'image_not_available': 'රූපය ලබා ගත නොහැක',
      'quantity': 'ප්‍රමාණය',
      'min_bid': 'අවම ලංසුව',
      'pickup_location': 'එකතු කරන ස්ථානය',
      'bidding_starts': 'ලංසු ආරම්භය',
      'time_until_start': 'ආරම්භය දක්වා කාලය',
      'time_left': 'ඉතිරි කාලය',
      'total_bids': 'මුළු ලංසු',
      'highest_bid': 'ඉහළම ලංසුව',
      'sold': 'විකුණා ඇත',
      'unknown': 'නොදනී',
      'bid_history': 'ලංසු ඉතිහාසය',
      'confirm': 'තහවුරු කරන්න',
      'no_bids_received': 'ලංසු ලැබී නැත',
      'winner': 'ජයග්‍රාහකයා',
      'sold_to': 'විකුණා ඇත',
      'delete_crop': 'බෝගය මකන්න',
      'delete_crop_confirm': 'ඔබට මකා දැමීමට අවශ්‍යද',
      'action_cannot_undone': 'මෙම ක්‍රියාව අහෝසි කළ නොහැක.',
      'crop_deleted_success': 'බෝගය සාර්ථකව මකා ඇත',
      'failed_to_delete': 'බෝගය මකා දැමීමට අසමත් විය',
      'bidding_history': 'ලංසු ඉතිහාසය',
      'bidding_summary': 'ලංසු සාරාංශය',
      'retry': 'නැවත උත්සාහ කරන්න',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'බෙදාහැරීම් ලුහුබැඳීම',
      'please_log_in': 'කරුණාකර පිවිසෙන්න',
      'no_deliveries': 'ප්‍රගතියේ බෙදාහැරීම් නැත',
      'delivery_tracking_desc': 'ප්‍රවාහන නියෝජිතයින් ඔබේ ඇණවුම් පිළිගත් පසු බෙදාහැරීම් ලුහුබැඳීම මෙහි දිස්වේ',
      'buyer': 'ගැනුම්කරු',
      'amount': 'මුදල',
      'pickup': 'එකතු කිරීම',
      'waiting_transporter': 'ප්‍රවාහනකරු සඳහා රැඳී සිටිමින්',
      'track_delivery': 'බෙදාහැරීම ලුහුබඳින්න',
      'confirm_received': 'ලැබීම තහවුරු කරන්න',
      'delivery_timeline': 'බෙදාහැරීම් කාල සටහන',
      'order_created': 'ඇණවුම නිර්මාණය කර ඇත',
      'transporter_accepted': 'ප්‍රවාහනකරු පිළිගෙන ඇත',
      'in_transit': 'ප්‍රවාහනයේ',
      'delivered': 'බෙදා හැර ඇත',
      'estimated_delivery': 'ඇස්තමේන්තුගත බෙදාහැරීම',
      'waiting': 'රැඳී සිටිමින්',
      'accepted': 'පිළිගත්',
      
      // Analytics Screen
      'analytics_earnings': 'විශ්ලේෂණ සහ ඉපැයීම්',
      'overview': 'දළ විශ්ලේෂණය',
      'earnings': 'ඉපැයීම්',
      'no_analytics_data': 'විශ්ලේෂණ දත්ත නොමැත',
      'key_metrics': 'ප්‍රධාන මිණුම්',
      'total_earnings': 'මුළු ඉපැයීම්',
      'completed_orders': 'සම්පූර්ණ කළ ඇණවුම්',
      'success_rate': 'සාර්ථක අනුපාතය',
      'avg_order_value': 'සාමාන්‍ය ඇණවුම් වටිනාකම',
      'total_crops_listed': 'ලැයිස්තුගත මුළු බෝග',
      'crops_sold': 'විකුණූ බෝග',
      'active_listings': 'සක්‍රිය ලැයිස්තු',
      'total_quantity_label': 'මුළු ප්‍රමාණය',
      'pending_orders': 'පොරොත්තු ඇණවුම්',
      'deliveries_completed': 'බෙදාහැරීම් සම්පූර්ණයි',
      'recent_activity': 'මෑත ක්‍රියාකාරකම්',
      'monthly_breakdown': 'මාසික බෙදීම',
      'month_jan': 'ජන',
      'month_feb': 'පෙබ',
      'month_mar': 'මාර්',
      'month_apr': 'අප්‍රේ',
      'month_may': 'මැයි',
      'month_jun': 'ජූනි',
      'month_jul': 'ජූලි',
      'month_aug': 'අගෝ',
      'month_sep': 'සැප්',
      'month_oct': 'ඔක්',
      'month_nov': 'නොවැ',
      'month_dec': 'දෙසැ',
      
      // Distributor Dashboard
      'distributor': 'බෙදාහරින්නා',
      'distributor_dashboard': 'බෙදාහරින්නා උපකරණ පුවරුව',
      'marketplace': 'වෙළඳපොළ',
      'my_orders': 'මගේ ඇණවුම්',
      'products': 'නිෂ්පාදන',
      'bid_analytics': 'ලංසු විශ්ලේෂණ',
      'active_auctions': 'සක්‍රිය වෙන්දේසි',
      'my_bids': 'මගේ ලංසු',
      'won_auctions': 'දිනූ වෙන්දේසි',
      'total_spent': 'මුළු වියදම',
      'leading_now': 'දැන් ඉදිරියෙන්',
      'ending_soon': 'ඉක්මනින් අවසන් වේ ≤24h',
      'last_7_days_trend': 'අවසන් දින 7 ලංසු ප්‍රවණතාව',
      'avg': 'සාමාන්‍ය',
      'win': 'ජය',
      'day': 'දිනය',
      'ending_soon_label': 'ඉක්මනින් අවසන් වේ',
      'ends_in': 'අවසන් වන්නේ',
      'you_are_leading': 'ඔබ ඉදිරියෙන් සිටී',
      'not_leading': 'ඉදිරියෙන් නැත',
      'top_spend_by_crop': 'බෝග අනුව ඉහළ වියදම',
      'last_7_days': 'අවසන් දින 7',
      'last_30_days': 'අවසන් දින 30',
      
      // Marketplace Screen
      'no_crops_available': 'බෝග නොමැත',
      'no_active_auctions': 'සක්‍රිය වෙන්දේසි හෝ දිනූ බෝග නැත',
      'current_highest': 'වර්තමාන ඉහළම',
      'your_bid': 'ඔබේ ලංසුව',
      'bidding_history_count': 'ලංසු ඉතිහාසය',
      'bids': 'ලංසු',
      'you_won_auction': 'ඔබ මෙම වෙන්දේසිය දිනුවා! අවසන් මිල',
      'sold_to_bidder': 'විකුණා ඇත',
      'highest_bidder': 'ඉහළම ලංසුකරු',
      'no_bids_placed': 'ලංසු තබා නැත - වෙන්දේසිය අවසන්',
      'place_order': 'ඇණවුම තබන්න',
      'auction_ended': 'වෙන්දේසිය අවසන්.',
      'won': 'දිනුවා',
      'update_bid': 'ලංසුව යාවත්කාලීන කරන්න',
      'place_bid': 'ලංසුව තබන්න',
      'place_your_bid': 'ඔබේ ලංසුව තබන්න',
      'your_bid_amount': 'ඔබේ ලංසු මුදල',
      'enter_amount_lkr': 'මුදල LKR වලින් ඇතුළත් කරන්න',
      'bid_must_be_at_least': 'ලංසුව අවම වශයෙන් විය යුතුය',
      'bid_placed_success': 'ලංසුව සාර්ථකව තබන ලදී!',
      'failed_place_bid': 'ලංසුව තැබීමට අසමත් විය',
      'update_your_bid': 'ඔබේ ලංසුව යාවත්කාලීන කරන්න',
      'your_current_bid': 'ඔබේ වර්තමාන ලංසුව',
      'new_bid_amount': 'නව ලංසු මුදල',
      'enter_new_amount': 'නව මුදල LKR වලින් ඇතුළත් කරන්න',
      'new_bid_must_be_higher': 'නව ලංසුව වැඩි විය යුතුය',
      'bid_updated_success': 'ලංසුව සාර්ථකව යාවත්කාලීන කරන ලදී!',
      'failed_update_bid': 'ලංසුව යාවත්කාලීන කිරීමට අසමත් විය',
      'close': 'වසන්න',
      
      // My Orders Screen
      'farmer_orders': 'ගොවි ඇණවුම්',
      'consumer_orders': 'පාරිභෝගික ඇණවුම්',
      
      // My Products Screen
      'delete_product': 'නිෂ්පාදනය මකන්න',
      'delete_product_confirm': 'ඔබට මකා දැමීමට අවශ්‍යද',
      'product_deleted_success': 'නිෂ්පාදනය සාර්ථකව මකා ඇත!',
      'no_products_yet': 'තවම නිෂ්පාදන නැත',
      'add_first_product': 'විකිණීම ආරම්භ කිරීමට ඔබේ පළමු නිෂ්පාදනය එකතු කරන්න',
      'add_product': 'නිෂ්පාදනය එකතු කරන්න',
      'search_products': 'නිෂ්පාදන සොයන්න...',
      'available': 'තිබේ',
      'low_stock': 'අඩු තොගය',
      'out_of_stock': 'තොගයෙන් බැහැර',
      'total_value': 'මුළු වටිනාකම',
      'set_baseline': 'මූලික සකස් කරන්න',
      'baseline_set': 'මූලික වත මන් ප්‍රමාණයට සකසා ඇත',
      'edit_product': 'නිෂ්පාදනය සංස්කරණය',
      'adjust_stock_kg': 'තොගය සකස් කරන්න (kg)',
      'apply': 'අයදුම් කරන්න',
      'stock_adjusted': 'තොගය සකසා ඇත',
      'inventory_overview': 'ඉන්වෙන්ටරි දළ විශ්ලේෂණය',
      
      // Errors
      'network_error': 'ජාල දෝෂය. කරුණාකර ඔබේ සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'unknown_error': 'නොදන්නා දෝෂයක් සිදු විය.',
      'auth_error': 'සත්‍යාපන දෝෂය.',
      
      // Transporter Dashboard
      'transporter_dashboard': 'ප්‍රවාහන උපකරණ පුවරුව',
      'my_transports': 'මගේ ප්‍රවාහන',
      'available_status': 'ලබා ගත හැකි',
      'hi': 'ආයුබෝවන්',
      'deliver_with_care': 'අද සැලකිල්ලෙන් බෙදාහරිමු',
      'available_deliveries': 'ලබා ගත හැකි බෙදාහැරීම්',
      'active_deliveries': 'සක්‍රිය බෙදාහැරීම්',
      'all_time': 'සියලු කාලයන්හි',
      'transport_orders': 'ප්‍රවාහන ඇණවුම්',
      'view_details': 'විස්තර බලන්න',
      'no_transport_orders': 'ප්‍රවාහන ඇණවුම් නැත',
      'no_transport_orders_desc': 'ඔබ බෙදාහැරීම් ඉල්ලීම් පිළිගත් පසු ප්‍රවාහන ඇණවුම් මෙහි දිස්වේ',
      'earnings_this_week': 'මෙම සතියේ ඉපැයීම්',
      'recent_deliveries': 'මෑත බෙදාහැරීම්',
      'from': 'සිට',
      'to': 'දක්වා',
      'completed_on': 'සම්පූර්ණ කළ දිනය',
      'no_recent_deliveries': 'මෑත බෙදාහැරීම් නැත',
      'start_delivering': 'ඔබේ ඉතිහාසය බැලීමට බෙදාහැරීම ආරම්භ කරන්න',
      'earnings_breakdown': 'ඉපැයීම් බෙදීම',
      'completed_deliveries': 'සම්පූර්ණ කළ බෙදාහැරීම්',
      'avg_earnings_per_delivery': 'බෙදාහැරීමකට සාමාන්‍ය ඉපැයීම',
      'total_distance_covered': 'ආවරණය කළ මුළු දුර',
      'performance_metrics': 'කාර්ය සාධන මිණුම්',
      'acceptance_rate': 'පිළිගැනීමේ අනුපාතය',
      'on_time_delivery': 'නියමිත වේලාවට බෙදාහැරීම',
      'customer_rating': 'පාරිභෝගික ශ්‍රේණිගත කිරීම',
      'earnings_trend': 'ඉපැයීම් ප්‍රවණතාව',
      'mon': 'සඳු',
      'tue': 'අඟ',
      'wed': 'බදා',
      'thu': 'බ්‍රහ',
      'fri': 'සිකු',
      'sat': 'සෙන',
      'sun': 'ඉරි',
      
      // Transporter Settings
      'transporter_settings': 'ප්‍රවාහන සැකසුම්',
      'vehicle_details': 'වාහන විස්තර',
      'manage_vehicle_info': 'ඔබේ වාහන තොරතුරු කළමනාකරණය කරන්න',
      'service_areas': 'සේවා ප්‍රදේශ',
      'set_service_areas': 'ඔබේ බෙදාහැරීම් සේවා ප්‍රදේශ සකසන්න',
      'maintenance_schedule': 'නඩත්තු කාලසටහන',
      'manage_maintenance': 'වාහන නඩත්තුව කළමනාකරණය කරන්න',
      'role_management': 'භූමිකා කළමනාකරණය',
      'current_transporter': 'වර්තමාන: ප්‍රවාහනකරු',
      'switch_role': 'භූමිකාව මාරු කරන්න',
      'select_role_to_switch': 'මාරු වීමට භූමිකාවක් තෝරන්න:',
      'switch_to_role': 'මාරු වන්න',
      'manage_notification_prefs': 'දැනුම්දීම් මනාපයන් කළමනාකරණය කරන්න',
      'privacy_security_settings': 'පෞද්ගලිකත්ව සහ ආරක්ෂක සැකසුම්',
      'get_help_support': 'උදව් සහ සහාය ලබා ගන්න',
      'app_info_version': 'යෙදුම් තොරතුරු සහ අනුවාදය',
      'profile_photo_updated': 'පැතිකඩ ඡායාරූපය යාවත්කාලීන කරන ලදී',
      'failed_update_photo': 'ඡායාරූපය යාවත්කාලීන කිරීමට අසමත් විය',
      'no_active_role_found': 'සක්‍රිය භූමිකාවක් හමු නොවීය',
      
      // Delivery Orders Screen
      'schedule': 'කාලසටහන',
      'no_available_deliveries': 'ලබා ගත හැකි බෙදාහැරීම් නැත',
      'new_delivery_orders_appear': 'නව බෙදාහැරීම් ඇණවුම් මෙහි දිස්වේ',
      'no_scheduled_deliveries': 'කාලසටහන්ගත බෙදාහැරීම් නැත',
      'tap_to_schedule': 'බෙදාහැරීම් කාලසටහන් කිරීමට දින දර්ශන නිරූපකය තට්ටු කරන්න',
      'dropoff': 'බහා දැමීම',
      'accept_delivery': 'බෙදාහැරීම පිළිගන්න',
      'schedule_delivery': 'බෙදාහැරීම කාලසටහන් කරන්න',
      'view_route': 'මාර්ගය බලන්න',
      'delivery_accepted': 'බෙදාහැරීම සාර්ථකව පිළිගෙන ඇත!',
      'failed_accept_delivery': 'බෙදාහැරීම පිළිගැනීමට අසමත් විය',
      'select_day': 'දිනය තෝරන්න',
      'scheduled_for': 'සඳහා කාලසටහන්ගත',
      'unschedule': 'කාලසටහන ඉවත් කරන්න',
      'accept_all_scheduled': 'සියලු කාලසටහන්ගත පිළිගන්න',
      'deliveries_for': 'සඳහා බෙදාහැරීම්',
      
      // Transport Orders Screen
      'all_orders': 'සියල්ල',
      'ongoing': 'ක්‍රියාත්මක',
      'no_orders_yet': 'තවම ඇණවුම් නැත',
      'orders_appear_here': 'පිළිගත් බෙදාහැරීම් ඇණවුම් මෙහි දිස්වේ',
      'no_accepted_transports': 'පිළිගත් ප්‍රවාහන නැත',
      'no_in_transit_transports': 'ප්‍රවාහනයේ ප්‍රවාහන නැත',
      'no_delivered_transports': 'බෙදා හැර ඇති ප්‍රවාහන නැත',
      'no_cancelled_transports': 'අවලංගු කළ ප්‍රවාහන නැත',
      'accepted_transports_appear': 'පිළිගත් ප්‍රවාහන ඇණවුම් මෙහි දිස්වේ',
      'in_transit_transports_appear': 'ප්‍රවාහනයේ ප්‍රවාහන ඇණවුම් මෙහි දිස්වේ',
      'delivered_transports_appear': 'බෙදා හැර ඇති ප්‍රවාහන ඇණවුම් මෙහි දිස්වේ',
      'cancelled_transports_appear': 'අවලංගු කළ ප්‍රවාහන ඇණවුම් මෙහි දිස්වේ',
      'pickup_at': 'එකතු කරන ස්ථානය',
      'deliver_to': 'බෙදාහරින ස්ථානය',
      'started_delivery': 'බෙදාහැරීම ආරම්භ කළා',
      'mark_delivered': 'බෙදාහැර ඇති ලෙස සලකුණු කරන්න',
      'order_delivered': 'ඇණවුම සාර්ථකව බෙදා හැර ඇති ලෙස සලකුණු කළා!',
      'failed_update_status': 'බෙදාහැරීම් තත්ත්වය යාවත්කාලීන කිරීමට අසමත් විය',
      'transport_order': 'ප්‍රවාහන ඇණවුම',
      'scheduled_delivery': 'කාලසටහන්ගත බෙදාහැරීම',
      'planned': 'සැලසුම්ගත',
      'specific_delivery_location': 'විශේෂිත බෙදාහරින ස්ථානය:',
      'delivery_fee': 'බෙදාහැරීම් ගාස්තුව',
      'open_in_maps': 'ගූගල් සිතියම් වල විවෘත කරන්න',
      'get_directions': 'මඟ පෙන්වීම් ලබා ගන්න',
      'provide_feedback': 'ප්‍රතිපෝෂණ ලබා දෙන්න',
      'rate_distributor': 'බෙදාහරින්නා ශ්‍රේණිගත කරන්න',
      'update_feedback': 'ප්‍රතිපෝෂණ යාවත්කාලීන කරන්න',
      'overall_rating': 'සමස්ත ශ්‍රේණිගත කිරීම',
      'what_stood_out': 'කුමක් කැපී පෙනුණාද? (අත්‍යවශ්‍ය නොවේ)',
      'comments_optional': 'අදහස් (අත්‍යවශ්‍ය නොවේ)',
      'suggestions_optional': 'යෝජනා (අත්‍යවශ්‍ය නොවේ)',
      'share_issues_highlights': 'බෙදාහරින්නා සමඟ කිසියම් ගැටළු හෝ විශේෂාංග බෙදා ගන්න...',
      'suggest_improvements': 'වේගවත් සහ සුමට බෙදාහැරීමක් සඳහා වැඩිදියුණු කිරීම් යෝජනා කරන්න...',
      'please_select_rating': 'කරුණාකර ශ්‍රේණිගත කිරීමක් තෝරන්න',
      'feedback_submitted': 'ප්‍රතිපෝෂණ ඉදිරිපත් කරන ලදී!',
      'feedback_updated': 'ප්‍රතිපෝෂණ යාවත්කාලීන කරන ලදී!',
      'failed_to_submit': 'ඉදිරිපත් කිරීමට අසමත් විය',
      
      // History Tab
      'no_delivery_history': 'බෙදාහැරීම් ඉතිහාසයක් නැත',
      'no_deliveries_found': 'බෙදාහැරීම් හමු නොවීය',
      'completed_deliveries_appear': 'සම්පූර්ණ කළ බෙදාහැරීම් මෙහි දිස්වේ',
      'try_different_period': 'වෙනත් කාල පරිච්ඡේදයක් තෝරන්න',
      'delivery_location': 'බෙදාහරින ස්ථානය',
      'total_orders': 'මුළු ඇණවුම්',
      'avg_order_earnings': 'ඇණවුමකට සාමාන්‍ය',
      'no_activity_yet': 'තවම ක්‍රියාකාරකම් නැත',
      'start_accepting_deliveries': 'විශ්ලේෂණ බැලීමට බෙදාහැරීම් පිළිගැනීම ආරම්භ කරන්න',
      
      // Earnings/Analytics
      'total_distance': 'මුළු දුර',
      'avg_per_delivery': 'බෙදාහැරීමකට සාමාන්‍ය',
      'this_month_earnings': 'මෙම මාසය',
      'filter_by': 'පෙරීම',
      'select_month': 'මාසය තෝරන්න',
      'january': 'ජනවාරි',
      'february': 'පෙබරවාරි',
      'march': 'මාර්තු',
      'april': 'අප්‍රේල්',
      'may': 'මැයි',
      'june': 'ජූනි',
      'july': 'ජූලි',
      'august': 'අගෝස්තු',
      'september': 'සැප්තැම්බර්',
      'october': 'ඔක්තෝබර්',
      'november': 'නොවැම්බර්',
      'december': 'දෙසැම්බර්',
      'no_earnings_data': 'ඉපැයීම් දත්ත නැත',
      'complete_deliveries_see_earnings': 'ඔබේ ඉපැයීම් මෙහි බැලීමට බෙදාහැරීම් සම්පූර්ණ කරන්න',
    },
    'ta': {
      // Auth
      'sign_up': 'பதிவு செய்க',
      'sign_in': 'உள்நுழைய',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'create_account': 'கணக்கு உருவாக்கு',
      'login': 'உள்நுழைய',
      'logout': 'வெளியேறு',
      
      // Role Selection
      'select_role': 'உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
      'role_description': 'உணவு சங்கிலியில் உங்கள் பங்கேற்பை சிறப்பாக விவரிக்கும் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
      'farmer': 'விவசாயி',
      'consumer': 'நுகர்வோர்',
      'food_distributor': 'உணவு விநியோகஸ்தர்',
      'transporter': 'போக்குவரத்து',
      'farmer_description': 'பயிர்களை வளர்த்து அறுவடை செய்தல், கால்நடைகளை வளர்த்தல்',
      'consumer_description': 'உணவு பொருட்களை வாங்கி பயன்படுத்துதல்',
      'distributor_description': 'சந்தைகளுக்கு உணவு பொருட்களை விநியோகித்தல்',
      'transporter_description': 'இடங்களுக்கு இடையே உணவு பொருட்களை போக்குவரத்து செய்தல்',
      'continue': 'தொடரவும்',
      
      // Onboarding
      'welcome': 'FarmLink க்கு வரவேற்கிறோம்',
      'connecting_farmers': 'விவசாயிகளை நுகர்வோருடன் இணைத்தல்',
      'fresh_produce': 'பண்ணையிலிருந்து நேரடியாக புதிய பொருட்கள்',
      'secure_transactions': 'பாதுகாப்பான மற்றும் வெளிப்படையான பரிவர்த்தனைகள்',
      'get_started': 'தொடங்கவும்',
      'skip': 'தவிர்க்கவும்',
      'next': 'அடுத்து',
      
      // Settings
      'settings': 'அமைப்புகள்',
      'switch_to_consumer': 'நுகர்வோருக்கு மாற்று',
      'language': 'மொழி',
      'language_changed': 'மொழி வெற்றிகரமாக மாற்றப்பட்டது',
      'profile': 'சுயவிவரம்',
      'notifications': 'அறிவிப்புகள்',
      'privacy': 'தனியுரிமை',
      'help': 'உதவி',
      'about': 'பற்றி',
      
      // Common
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'cancel': 'ரத்து செய்',
      'save': 'சேமி',
      'delete': 'அழி',
      'edit': 'திருத்து',
      'back': 'பின்செல்',
      'home': 'முகப்பு',
      'history': 'வரலாறு',
      'search': 'தேடு',
      'menu': 'மெனு',
      
      // Validation
      'email_required': 'மின்னஞ்சல் தேவை',
      'password_required': 'கடவுச்சொல் தேவை',
      'confirm_password_required': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'passwords_dont_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'password_too_short': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
      'invalid_email': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      
      // Dashboard
      'dashboard': 'டாஷ்போர்டு',
      'my_products': 'எனது பொருட்கள்',
      'orders': 'ஆர்டர்கள்',
      'analytics': 'பகுப்பாய்வு',
      'messages': 'செய்திகள்',
      
      // Farmer Dashboard
      'crops': 'பயிர்கள்',
      'delivery': 'விநியோகம்',
      'hello': 'வணக்கம்',
      'farm_statistics': 'பண்ணை புள்ளிவிவரங்கள்',
      'active_crops': 'செயல்படும் பயிர்கள்',
      'sold_crops': 'விற்கப்பட்ட பயிர்கள்',
      'pending_crops': 'நிலுவையில் உள்ள பயிர்கள்',
      'this_month': 'இந்த மாதம்',
      'quick_actions': 'விரைவு செயல்கள்',
      'add_new_crop': 'புதிய பயிர் சேர்க்கவும்',
      'add_new_crop_desc': 'ஏலத்திற்கு உங்கள் புதிய பொருட்களை பட்டியலிடவும்',
      'ai_crop_advisory': 'AI பயிர் ஆலோசனை',
      'ai_crop_advisory_desc': 'AI-இயக்கப்பட்ட விவசாய ஆலோசனை மற்றும் நுண்ணறிவுகளைப் பெறவும்',
      'weather_forecast': 'வானிலை முன்னறிவிப்பு',
      'weather_forecast_desc': 'விவசாய முடிவுகளுக்கான வானிலை நிலைமைகளை சரிபார்க்கவும்',
      'refresh_statistics': 'புள்ளிவிவரங்களை புதுப்பிக்கவும்',
      
      // Weather
      'weather_forecast_title': 'வானிலை முன்னறிவிப்பு',
      'real_time_weather': 'நேரடி வானிலை தரவு',
      'loading_weather': 'வானிலை தரவை ஏற்றுகிறது...',
      'current_location': 'தற்போதைய இடம்',
      'select_city': 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
      'current_weather': 'தற்போதைய வானிலை',
      'farming_recommendations': 'விவசாய பரிந்துரைகள்',
      'irrigation': 'நீர்ப்பாசனம்',
      'planting': 'நடவு',
      'pest_control': 'பூச்சி கட்டுப்பாடு',
      'refresh_weather': 'வானிலை தரவை புதுப்பிக்கவும்',
      'humidity': 'ஈரப்பதம்',
      'wind': 'காற்று',
      'pressure': 'அழுத்தம்',
      
      // Crop Listing Screen
      'my_crops': 'எனது பயிர்கள்',
      'pending': 'நிலுவையில்',
      'active': 'செயல்படும்',
      'expired': 'காலாவதியானது',
      'all': 'அனைத்தும்',
      'no_pending_crops': 'நிலுவையில் உள்ள பயிர்கள் இல்லை',
      'no_active_crops': 'செயல்படும் பயிர்கள் இல்லை',
      'no_expired_crops': 'காலாவதியான பயிர்கள் இல்லை',
      'no_crops_found': 'பயிர்கள் கிடைக்கவில்லை',
      'start_adding_crops': 'இங்கே காண பயிர்களைச் சேர்க்கத் தொடங்குங்கள்',
      'image_not_available': 'படம் கிடைக்கவில்லை',
      'quantity': 'அளவு',
      'min_bid': 'குறைந்தபட்ச ஏலம்',
      'pickup_location': 'எடுக்கும் இடம்',
      'bidding_starts': 'ஏலம் தொடங்கும்',
      'time_until_start': 'தொடக்கம் வரை நேரம்',
      'time_left': 'மீதமுள்ள நேரம்',
      'total_bids': 'மொத்த ஏலங்கள்',
      'highest_bid': 'அதிகபட்ச ஏலம்',
      'sold': 'விற்கப்பட்டது',
      'unknown': 'தெரியாத',
      'bid_history': 'ஏல வரலாறு',
      'confirm': 'உறுதிப்படுத்து',
      'no_bids_received': 'ஏலங்கள் பெறப்படவில்லை',
      'winner': 'வெற்றியாளர்',
      'sold_to': 'விற்கப்பட்டது',
      'delete_crop': 'பயிரை அழி',
      'delete_crop_confirm': 'நீங்கள் நிச்சயமாக அழிக்க விரும்புகிறீர்களா',
      'action_cannot_undone': 'இந்த செயலை மாற்ற இயலாது.',
      'crop_deleted_success': 'பயிர் வெற்றிகரமாக அழிக்கப்பட்டது',
      'failed_to_delete': 'பயிரை அழிக்க தோல்வி',
      'bidding_history': 'ஏல வரலாறு',
      'bidding_summary': 'ஏல சுருக்கம்',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      
      // Delivery Tracking Screen
      'delivery_tracking': 'விநியோக கண்காணிப்பு',
      'please_log_in': 'தயவுசெய்து உள்நுழையவும்',
      'no_deliveries': 'விநியோகங்கள் முன்னேற்றத்தில் இல்லை',
      'delivery_tracking_desc': 'போக்குவரத்து நிறுவனங்கள் உங்கள் ஆர்டர்களை ஏற்றுக்கொண்டதும் விநியோக கண்காணிப்பு இங்கே தோன்றும்',
      'buyer': 'வாங்குபவர்',
      'amount': 'தொகை',
      'pickup': 'எடுத்தல்',
      'waiting_transporter': 'போக்குவரத்துக்காக காத்திருக்கிறது',
      'track_delivery': 'விநியோகத்தைக் கண்காணிக்கவும்',
      'confirm_received': 'பெறப்பட்டதை உறுதிப்படுத்து',
      'delivery_timeline': 'விநியோக காலவரிசை',
      'order_created': 'ஆர்டர் உருவாக்கப்பட்டது',
      'transporter_accepted': 'போக்குவரத்து ஏற்றுக்கொள்ளப்பட்டது',
      'in_transit': 'போக்குவரத்தில்',
      'delivered': 'வழங்கப்பட்டது',
      'estimated_delivery': 'மதிப்பிடப்பட்ட விநியோகம்',
      'waiting': 'காத்திருக்கிறது',
      'accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
      
      // Analytics Screen
      'analytics_earnings': 'பகுப்பாய்வு & வருமானம்',
      'overview': 'கண்ணோட்டம்',
      'earnings': 'வருமானம்',
      'no_analytics_data': 'பகுப்பாய்வு தரவு கிடைக்கவில்லை',
      'key_metrics': 'முக்கிய அளவீடுகள்',
      'total_earnings': 'மொத்த வருமானம்',
      'completed_orders': 'முடிக்கப்பட்ட ஆர்டர்கள்',
      'success_rate': 'வெற்றி விகிதம்',
      'avg_order_value': 'சராசரி ஆர்டர் மதிப்பு',
      'total_crops_listed': 'பட்டியலிடப்பட்ட மொத்த பயிர்கள்',
      'crops_sold': 'விற்கப்பட்ட பயிர்கள்',
      'active_listings': 'செயல்படும் பட்டியல்கள்',
      'total_quantity_label': 'மொத்த அளவு',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'deliveries_completed': 'விநியோகங்கள் முடிந்தது',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'monthly_breakdown': 'மாதாந்திர பிரிவு',
      'month_jan': 'ஜன',
      'month_feb': 'பிப்',
      'month_mar': 'மார்',
      'month_apr': 'ஏப்',
      'month_may': 'மே',
      'month_jun': 'ஜூன்',
      'month_jul': 'ஜூலை',
      'month_aug': 'ஆக',
      'month_sep': 'செப்',
      'month_oct': 'அக்',
      'month_nov': 'நவ',
      'month_dec': 'டிச',
      
      // Distributor Dashboard
      'distributor': 'விநியோகஸ்தர்',
      'distributor_dashboard': 'விநியோகஸ்தர் டாஷ்போர்டு',
      'marketplace': 'சந்தை',
      'my_orders': 'எனது ஆர்டர்கள்',
      'products': 'பொருட்கள்',
      'bid_analytics': 'ஏல பகுப்பாய்வு',
      'active_auctions': 'செயல்படும் ஏலங்கள்',
      'my_bids': 'எனது ஏலங்கள்',
      'won_auctions': 'வென்ற ஏலங்கள்',
      'total_spent': 'மொத்த செலவு',
      'leading_now': 'இப்போது முன்னணியில்',
      'ending_soon': 'விரைவில் முடியும் ≤24h',
      'last_7_days_trend': 'கடந்த 7 நாட்கள் ஏல போக்கு',
      'avg': 'சரா',
      'win': 'வெற்றி',
      'day': 'நாள்',
      'ending_soon_label': 'விரைவில் முடியும்',
      'ends_in': 'முடியும் நேரம்',
      'you_are_leading': 'நீங்கள் முன்னணியில் உள்ளீர்கள்',
      'not_leading': 'முன்னணியில் இல்லை',
      'top_spend_by_crop': 'பயிர் வாரியாக அதிக செலவு',
      'last_7_days': 'கடந்த 7 நாட்கள்',
      'last_30_days': 'கடந்த 30 நாட்கள்',
      
      // Marketplace Screen
      'no_crops_available': 'பயிர்கள் இல்லை',
      'no_active_auctions': 'செயல்படும் ஏலங்கள் அல்லது வென்ற பயிர்கள் இல்லை',
      'current_highest': 'தற்போதைய அதிகபட்சம்',
      'your_bid': 'உங்கள் ஏலம்',
      'bidding_history_count': 'ஏல வரலாறு',
      'bids': 'ஏலங்கள்',
      'you_won_auction': 'நீங்கள் இந்த ஏலத்தை வென்றீர்கள்! இறுதி விலை',
      'sold_to_bidder': 'விற்கப்பட்டது',
      'highest_bidder': 'அதிகபட்ச ஏலதாரர்',
      'no_bids_placed': 'ஏலங்கள் வைக்கப்படவில்லை - ஏலம் முடிந்தது',
      'place_order': 'ஆர்டர் செய்யவும்',
      'auction_ended': 'ஏலம் முடிந்தது.',
      'won': 'வென்றது',
      'update_bid': 'ஏலத்தை புதுப்பிக்கவும்',
      'place_bid': 'ஏலம் வைக்கவும்',
      'place_your_bid': 'உங்கள் ஏலத்தை வைக்கவும்',
      'your_bid_amount': 'உங்கள் ஏல தொகை',
      'enter_amount_lkr': 'தொகையை LKR இல் உள்ளிடவும்',
      'bid_must_be_at_least': 'ஏலம் குறைந்தபட்சம் இருக்க வேண்டும்',
      'bid_placed_success': 'ஏலம் வெற்றிகரமாக வைக்கப்பட்டது!',
      'failed_place_bid': 'ஏலம் வைக்க தோல்வி',
      'update_your_bid': 'உங்கள் ஏலத்தை புதுப்பிக்கவும்',
      'your_current_bid': 'உங்கள் தற்போதைய ஏலம்',
      'new_bid_amount': 'புதிய ஏல தொகை',
      'enter_new_amount': 'புதிய தொகையை LKR இல் உள்ளிடவும்',
      'new_bid_must_be_higher': 'புதிய ஏலம் அதிகமாக இருக்க வேண்டும்',
      'bid_updated_success': 'ஏலம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'failed_update_bid': 'ஏலத்தை புதுப்பிக்க தோல்வி',
      'close': 'மூடு',
      
      // My Orders Screen
      'farmer_orders': 'விவசாயி ஆர்டர்கள்',
      'consumer_orders': 'நுகர்வோர் ஆர்டர்கள்',
      
      // My Products Screen
      'delete_product': 'பொருளை அழி',
      'delete_product_confirm': 'நீங்கள் நிச்சயமாக அழிக்க விரும்புகிறீர்களா',
      'product_deleted_success': 'பொருள் வெற்றிகரமாக அழிக்கப்பட்டது!',
      'no_products_yet': 'இன்னும் பொருட்கள் இல்லை',
      'add_first_product': 'விற்பனையைத் தொடங்க உங்கள் முதல் பொருளைச் சேர்க்கவும்',
      'add_product': 'பொருள் சேர்க்கவும்',
      'search_products': 'பொருட்களைத் தேடுங்கள்...',
      'available': 'கிடைக்கிறது',
      'low_stock': 'குறைந்த இருப்பு',
      'out_of_stock': 'இருப்பில் இல்லை',
      'total_value': 'மொத்த மதிப்பு',
      'set_baseline': 'அடிப்படை அமை',
      'baseline_set': 'அடிப்படை தற்போதைய அளவுக்கு அமைக்கப்பட்டது',
      'edit_product': 'பொருளைத் திருத்து',
      'adjust_stock_kg': 'இருப்பை சரிசெய் (kg)',
      'apply': 'பயன்படுத்து',
      'stock_adjusted': 'இருப்பு சரிசெய்யப்பட்டது',
      'inventory_overview': 'சரக்கு கண்ணோட்டம்',
      
      // Errors
      'network_error': 'பிணைய பிழை. உங்கள் இணைப்பை சரிபார்க்கவும்.',
      'unknown_error': 'தெரியாத பிழை ஏற்பட்டது.',
      'auth_error': 'அங்கீகார பிழை.',
      
      // Transporter Dashboard
      'transporter_dashboard': 'போக்குவரத்து டாஷ்போர்டு',
      'my_transports': 'எனது போக்குவரத்து',
      'available_status': 'கிடைக்கிறது',
      'hi': 'வணக்கம்',
      'deliver_with_care': 'இன்று கவனமாக வழங்குவோம்',
      'available_deliveries': 'கிடைக்கும் விநியோகங்கள்',
      'active_deliveries': 'செயல்படும் விநியோகங்கள்',
      'all_time': 'எல்லா காலமும்',
      'transport_orders': 'போக்குவரத்து ஆர்டர்கள்',
      'view_details': 'விவரங்களைக் காண்க',
      'no_transport_orders': 'போக்குவரத்து ஆர்டர்கள் இல்லை',
      'no_transport_orders_desc': 'நீங்கள் விநியோக கோரிக்கைகளை ஏற்றுக்கொண்டதும் போக்குவரத்து ஆர்டர்கள் இங்கே தோன்றும்',
      'earnings_this_week': 'இந்த வார வருமானம்',
      'recent_deliveries': 'சமீபத்திய விநியோகங்கள்',
      'from': 'இருந்து',
      'to': 'வரை',
      'completed_on': 'முடிக்கப்பட்ட தேதி',
      'no_recent_deliveries': 'சமீபத்திய விநியோகங்கள் இல்லை',
      'start_delivering': 'உங்கள் வரலாற்றைக் காண விநியோகத்தைத் தொடங்குங்கள்',
      'earnings_breakdown': 'வருமான பிரிவு',
      'completed_deliveries': 'முடிக்கப்பட்ட விநியோகங்கள்',
      'avg_earnings_per_delivery': 'விநியோகத்திற்கான சராசரி வருமானம்',
      'total_distance_covered': 'மொத்த தூரம் கடக்கப்பட்டது',
      'performance_metrics': 'செயல்திறன் அளவீடுகள்',
      'acceptance_rate': 'ஏற்றுக்கொள்ளும் விகிதம்',
      'on_time_delivery': 'சரியான நேரத்தில் விநியோகம்',
      'customer_rating': 'வாடிக்கையாளர் மதிப்பீடு',
      'earnings_trend': 'வருமான போக்கு',
      'mon': 'திங்',
      'tue': 'செவ்',
      'wed': 'புத',
      'thu': 'வியா',
      'fri': 'வெள்',
      'sat': 'சனி',
      'sun': 'ஞாயி',
      
      // Transporter Settings
      'transporter_settings': 'போக்குவரத்து அமைப்புகள்',
      'vehicle_details': 'வாகன விவரங்கள்',
      'manage_vehicle_info': 'உங்கள் வாகன தகவலை நிர்வகிக்கவும்',
      'service_areas': 'சேவை பகுதிகள்',
      'set_service_areas': 'உங்கள் விநியோக சேவை பகுதிகளை அமைக்கவும்',
      'maintenance_schedule': 'பராமரிப்பு அட்டவணை',
      'manage_maintenance': 'வாகன பராமரிப்பை நிர்வகிக்கவும்',
      'role_management': 'பாத்திர நிர்வாகம்',
      'current_transporter': 'தற்போதைய: போக்குவரத்து',
      'switch_role': 'பாத்திரத்தை மாற்று',
      'select_role_to_switch': 'மாற்ற ஒரு பாத்திரத்தைத் தேர்ந்தெடுக்கவும்:',
      'switch_to_role': 'மாற்று',
      'manage_notification_prefs': 'அறிவிப்பு விருப்பங்களை நிர்வகிக்கவும்',
      'privacy_security_settings': 'தனியுரிமை மற்றும் பாதுகாப்பு அமைப்புகள்',
      'get_help_support': 'உதவி மற்றும் ஆதரவைப் பெறுங்கள்',
      'app_info_version': 'பயன்பாட்டு தகவல் மற்றும் பதிப்பு',
      'profile_photo_updated': 'சுயவிவர புகைப்படம் புதுப்பிக்கப்பட்டது',
      'failed_update_photo': 'புகைப்படத்தை புதுப்பிக்க தோல்வி',
      'no_active_role_found': 'செயல்படும் பாத்திரம் கிடைக்கவில்லை',
      
      // Delivery Orders Screen
      'schedule': 'அட்டவணை',
      'no_available_deliveries': 'கிடைக்கும் விநியோகங்கள் இல்லை',
      'new_delivery_orders_appear': 'புதிய விநியோக ஆர்டர்கள் இங்கே தோன்றும்',
      'no_scheduled_deliveries': 'திட்டமிடப்பட்ட விநியோகங்கள் இல்லை',
      'tap_to_schedule': 'விநியோகங்களைத் திட்டமிட காலெண்டர் ஐகானைத் தட்டவும்',
      'dropoff': 'இறக்கல்',
      'accept_delivery': 'விநியோகத்தை ஏற்கவும்',
      'schedule_delivery': 'விநியோகத்தைத் திட்டமிடவும்',
      'view_route': 'பாதையைக் காண்க',
      'delivery_accepted': 'விநியோகம் வெற்றிகரமாக ஏற்றுக்கொள்ளப்பட்டது!',
      'failed_accept_delivery': 'விநியோகத்தை ஏற்க தோல்வி',
      'select_day': 'நாளைத் தேர்ந்தெடுக்கவும்',
      'scheduled_for': 'க்கு திட்டமிடப்பட்டது',
      'unschedule': 'அட்டவணையை நீக்கு',
      'accept_all_scheduled': 'அனைத்து திட்டமிடப்பட்டவையையும் ஏற்கவும்',
      'deliveries_for': 'க்கான விநியோகங்கள்',
      
      // Transport Orders Screen
      'all_orders': 'அனைத்தும்',
      'ongoing': 'செயலில்',
      'no_orders_yet': 'இன்னும் ஆர்டர்கள் இல்லை',
      'orders_appear_here': 'ஏற்றுக்கொள்ளப்பட்ட விநியோக ஆர்டர்கள் இங்கே தோன்றும்',
      'no_accepted_transports': 'ஏற்றுக்கொள்ளப்பட்ட போக்குவரத்து இல்லை',
      'no_in_transit_transports': 'போக்குவரத்தில் உள்ள போக்குவரத்து இல்லை',
      'no_delivered_transports': 'வழங்கப்பட்ட போக்குவரத்து இல்லை',
      'no_cancelled_transports': 'ரத்து செய்யப்பட்ட போக்குவரத்து இல்லை',
      'accepted_transports_appear': 'ஏற்றுக்கொள்ளப்பட்ட போக்குவரத்து ஆர்டர்கள் இங்கே தோன்றும்',
      'in_transit_transports_appear': 'போக்குவரத்தில் உள்ள போக்குவரத்து ஆர்டர்கள் இங்கே தோன்றும்',
      'delivered_transports_appear': 'வழங்கப்பட்ட போக்குவரத்து ஆர்டர்கள் இங்கே தோன்றும்',
      'cancelled_transports_appear': 'ரத்து செய்யப்பட்ட போக்குவரத்து ஆர்டர்கள் இங்கே தோன்றும்',
      'pickup_at': 'எடுக்கும் இடம்',
      'deliver_to': 'வழங்கும் இடம்',
      'started_delivery': 'விநியோகம் தொடங்கியது',
      'mark_delivered': 'வழங்கப்பட்டதாகக் குறிக்கவும்',
      'order_delivered': 'ஆர்டர் வெற்றிகரமாக வழங்கப்பட்டதாகக் குறிக்கப்பட்டது!',
      'failed_update_status': 'விநியோக நிலையைப் புதுப்பிக்க தோல்வி',
      'transport_order': 'போக்குவரத்து ஆர்டர்',
      'scheduled_delivery': 'திட்டமிடப்பட்ட விநியோகம்',
      'planned': 'திட்டமிடப்பட்டது',
      'specific_delivery_location': 'குறிப்பிட்ட விநியோக இடம்:',
      'delivery_fee': 'விநியோக கட்டணம்',
      'open_in_maps': 'கூகுள் மேப்ஸில் திறக்கவும்',
      'get_directions': 'திசைகளைப் பெறுங்கள்',
      'provide_feedback': 'கருத்து வழங்கவும்',
      'rate_distributor': 'விநியோகஸ்தரை மதிப்பிடவும்',
      'update_feedback': 'கருத்தைப் புதுப்பிக்கவும்',
      'overall_rating': 'ஒட்டுமொத்த மதிப்பீடு',
      'what_stood_out': 'என்ன தனித்துவமாக இருந்தது? (விருப்பமானது)',
      'comments_optional': 'கருத்துகள் (விருப்பமானது)',
      'suggestions_optional': 'பரிந்துரைகள் (விருப்பமானது)',
      'share_issues_highlights': 'விநியோகஸ்தருடன் ஏதேனும் சிக்கல்கள் அல்லது சிறப்பம்சங்களைப் பகிரவும்...',
      'suggest_improvements': 'வேகமான மற்றும் சுமூகமான விநியோகத்திற்கான மேம்பாடுகளை பரிந்துரைக்கவும்...',
      'please_select_rating': 'மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
      'feedback_submitted': 'கருத்து சமர்ப்பிக்கப்பட்டது!',
      'feedback_updated': 'கருத்து புதுப்பிக்கப்பட்டது!',
      'failed_to_submit': 'சமர்ப்பிக்க தோல்வி',
      
      // History Tab
      'no_delivery_history': 'விநியோக வரலாறு இல்லை',
      'no_deliveries_found': 'விநியோகங்கள் கிடைக்கவில்லை',
      'completed_deliveries_appear': 'முடிக்கப்பட்ட விநியோகங்கள் இங்கே தோன்றும்',
      'try_different_period': 'வேறு காலப்பகுதியைத் தேர்ந்தெடுக்க முயற்சிக்கவும்',
      'delivery_location': 'வழங்கும் இடம்',
      'total_orders': 'மொத்த ஆர்டர்கள்',
      'avg_order_earnings': 'ஆர்டருக்கு சராசரி',
      'no_activity_yet': 'இன்னும் செயல்பாடு இல்லை',
      'start_accepting_deliveries': 'பகுப்பாய்வுகளைக் காண விநியோகங்களை ஏற்கத் தொடங்குங்கள்',
      
      // Earnings/Analytics
      'total_distance': 'மொத்த தூரம்',
      'avg_per_delivery': 'விநியோகத்திற்கு சராசரி',
      'this_month_earnings': 'இந்த மாதம்',
      'filter_by': 'பிரிக்கவும்',
      'select_month': 'மாதத்தைத் தேர்ந்தெடுக்கவும்',
      'january': 'ஜனவரி',
      'february': 'பிப்ரவரி',
      'march': 'மார்ச்',
      'april': 'ஏப்ரல்',
      'may': 'மே',
      'june': 'ஜூன்',
      'july': 'ஜூலை',
      'august': 'ஆகஸ்ட்',
      'september': 'செப்டம்பர்',
      'october': 'அக்டோபர்',
      'november': 'நவம்பர்',
      'december': 'டிசம்பர்',
      'no_earnings_data': 'வருமான தரவு இல்லை',
      'complete_deliveries_see_earnings': 'உங்கள் வருமானத்தை இங்கே காண விநியோகங்களை முடிக்கவும்',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['en']![key] ?? 
           key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'si', 'ta'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
